### ISSUE TITLE
Version 1.1.1 doesn't work on second install

### ISSUE THREAD

**Issue by thomaseyde** [jfromaniello/nestin#3]
I installed NestIn after I installed File Nesting and got an extension conflict type of error message, so I uninstalled both of them.

After I reinstalled NestIn, nothing happens when I select "Nest item".

I use VS 2012.

**Comment by jeremysimmons** [comment]
@thomaseyde  I helped a developer resolve a similar issue today where the extension installs, and you have context menu items, but when clicked on, "nothing happens".

Open this file in a web-browser. 
"C:\Users<username>\AppData\Roaming\Microsoft\VisualStudio\11.0\ActivityLog.xml"

Also if you check the Fusion Bind Errors [How to enable assembly bind failure logging (Fusion) in .NET](http://stackoverflow.com/questions/255669/how-to-enable-assembly-bind-failure-logging-fusion-in-net), you will probably have an entry for Microsoft.VisualStudio.Shell.10.0, Version=12.0.0.0, being called from NestIn.dll.

If so, this is the same issue as https://github.com/jfromaniello/nestin/issues/2.

**Comment by jeremysimmons** [comment]
Issue abandoned by OP
